exclude: 'extern'
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v14.0.5'  # Use the sha / tag you want to point at
    hooks:
    -   id: clang-format
        types_or: [c++, c]
