exclude: 'extern'
repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v14.0.5'  # Use the sha / tag you want to point at
  hooks:
  - id: clang-format
    types_or: [c++, c]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: 'v9.4.0'
  hooks:
  - id: commitlint
    stages: [commit-msg]