function(include_unity)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/extern/unity)
endfunction()

function(enV5_init)
    # add runtime.c
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/extern/elastic-ai.runtime.c)
    add_library(CException INTERFACE)
    target_sources(CException INTERFACE ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/extern/cexception/lib/CException.c)
    target_include_directories(CException INTERFACE ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/extern/cexception/lib)

    include_directories(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src)
    # libraries from the elastic-ai.runtime.enV5 repo
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/adxl345b)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/atCommands)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/broker)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/enV5HwController)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/esp)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/flash)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/fpgaConfigurationHandler)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/freeRtos)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/gpio)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/http)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/i2c)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/middleware)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/network)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/pac193x)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/sht3x)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/sleep)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/spi)
    add_subdirectory(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/src/uart)
endfunction()
