function(fetch_git_submodules)
    find_package(Git QUIET)
    message("${PROJECT_SOURCE_DIR}/.git")
    if(GIT_FOUND AND EXISTS "${PROJECT_SOURCE_DIR}/.git")
        # Update Submodules
        option(GIT_SUBMODULE "Check submodules build" ON)
        if(GIT_SUBMODULE)
            message(STATUS "Submodule update")
            execute_process(COMMAND ${GIT_EXECUTABLE} submodule update --init --recursive
                    WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}
                    RESULT_VARIABLE GIT_SUBMOD_RESULT)
            if(NOT GIT_SUBMOD_RESULT EQUAL "0")
                message(FATAL_ERROR "git submodule update --init failed with ${GIT_SUBMOD_RESULT}")
            endif()
        endif()
    endif()
endfunction()

function(include_src)
    add_subdirectory(src/broker)
    add_subdirectory(src/esp)
    add_subdirectory(src/FreeRTOSUtils)
    add_subdirectory(src/gpio)
    add_subdirectory(src/i2c)
    add_subdirectory(src/network)
    add_subdirectory(src/uart)
endfunction()

function(include_pico)
    # initialize pico-sdk from GIT (note this can come from environment, CMake cache etc)
    set(PICO_SDK_FETCH_FROM_GIT 1)
    # pico_sdk_import.cmake is a single file copied from this SDK, note: this must happen before project()
    include(extern/pico-sdk/pico_sdk_import.cmake)
    pico_sdk_init() # initialize the Raspberry Pi Pico SDK
endfunction()
