#ifndef ENV5_FREERTOS_TASKWRAPPER_INTERNAL_HEADER
#define ENV5_FREERTOS_TASKWRAPPER_INTERNAL_HEADER

static void freeRtosTaskWrapperInternalInvokeTaskCode(void *p_taskCode);

#endif /* ENV5_FREERTOS_TASKWRAPPER_INTERNAL_HEADER */
