#include "at_commands.h"

char AT_DISABLE_ECHO[] = "ATE0";
size_t AT_DISABLE_ECHO_LENGTH = 5;
char AT_DISABLE_ECHO_RESPONSE[] = "OK";

char AT_RESTART[] = "AT+RST";
size_t AT_RESTART_LENGTH = 7;
char AT_RESTART_RESPONSE[] = "OK";

char AT_DISABLE_MULTI_CONNECT[] = "AT+CIPMUX=0";
size_t AT_DISABLE_MULTI_CONNECT_LENGTH = 12;
char AT_DISABLE_MULTI_CONNECT_RESPONSE[] = "OK";

char AT_CONNECT_TO_NETWORK[] = "AT+CWJAP=\"%s\",\"%s\",,1,5,3,0,120";
size_t AT_CONNECT_TO_NETWORK_LENGTH = 28;
char AT_CONNECT_TO_NETWORK_RESPONSE[] = "WIFI CONNECTED";

char AT_DISCONNECT[] = "AT+CWQAP";
size_t AT_DISCONNECT_LENGTH = 9;
char AT_DISCONNECT_RESPONSE[] = "OK";
