[project]
authors = [
    { name = "Intelligent Embedded Systems - University Duisburg Essen" },
]
license = { text = "MIT" }
name = "elasticai.runtime.bitfilescripts"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "pyserial>=3.5",
]
