[project]
name = "testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
testing = "testing:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
