/*
 * This is an autogenerated stub.
 * Do not change it manually.
 */

#include "echo_server.h"
#include "./middleware.h"
#include "Sleep.h"

#include <stdbool.h>
#include <stdint.h>

#define ADDR_SKELETON_INPUTS 0
#define ADDR_COMPUTATION_ENABLE 100

static void modelCompute(bool enable);
static uint8_t get_id(void);

static uint64_t accelerator_id = 50;
static uint32_t accelerator_addr = 0;

bool echo_server_deploy(void) {
    middlewareInit();
    middlewareConfigureFpga(accelerator_addr);
    sleep_for_ms(200);
    bool is_deployed_successfully = (get_id() == accelerator_id);
    middlewareDeinit();
    return is_deployed_successfully;
}

int8_t echo_server_echo(int8_t inputs) {
    int8_t _result;

    middlewareInit();
    middlewareUserlogicEnable();
    middlewareWriteBlocking(ADDR_SKELETON_INPUTS + 0, (uint8_t *)(&inputs), 1);
    modelCompute(true);

    while (middlewareUserlogicGetBusyStatus())
        ;
    modelCompute(false);
    for (int i = 0; i < 1; i++) {
        middlewareReadBlocking(ADDR_SKELETON_INPUTS + 0 + i, (uint8_t *)(&_result) + i, 1);
        middlewareReadBlocking(ADDR_SKELETON_INPUTS + 0 + i, (uint8_t *)(&_result) + i, 1);
    }
    middlewareUserlogicDisable();
    middlewareDeinit();
    return _result;
}

static void modelCompute(bool enable) {
    uint8_t cmd = (enable ? 1 : 0);
    middlewareWriteBlocking(ADDR_COMPUTATION_ENABLE, &cmd, 1);
}

static uint8_t get_id(void) {
    middlewareUserlogicEnable();
    uint8_t id = middlewareGetDesignId();
    middlewareUserlogicDisable();
    return id;
}
