set(EAI_VALID_MCUS HOST RP2040 RP2350)
set(EAI_VALID_BOARDS NONE PICO PICO_W ENV5)
set(EAI_VALID_ENV5_REVS 1 2)

if (NOT EAI_TARGET_PLATFORM_MCU IN_LIST EAI_VALID_MCUS)
    message(FATAL_ERROR "-DEAI_TARGET_PLATFORM_MCU=<mcu> required, one of ${EAI_VALID_MCUS}")
endif ()
if (NOT EAI_TARGET_PLATFORM_BOARD IN_LIST EAI_VALID_BOARDS)
    message(FATAL_ERROR "-DEAI_TARGET_PLATFORM_BOARD=<board> required, one of ${EAI_VALID_BOARDS}")
endif ()

if (EAI_TARGET_PLATFORM_BOARD STREQUAL ENV5
        AND NOT EAI_TARGET_PLATFORM_REVISION IN_LIST EAI_VALID_ENV5_REVS)
    message(FATAL_ERROR
            "-DEAI_TARGET_PLATFORM_REVISION=<1|2> required when EAI_TARGET_PLATFORM_BOARD=ENV5"
    )
endif ()

if (EAI_TARGET_PLATFORM_MCU STREQUAL HOST AND EAI_TARGET_PLATFORM_BOARD STREQUAL NONE)
    include(${CMAKE_CURRENT_LIST_DIR}/targets/host.cmake)

elseif (EAI_TARGET_PLATFORM_MCU STREQUAL RP2040 AND EAI_TARGET_PLATFORM_BOARD MATCHES "PICO")
    include(${CMAKE_CURRENT_LIST_DIR}/targets/pico.cmake)

elseif (EAI_TARGET_PLATFORM_MCU STREQUAL RP2040 AND EAI_TARGET_PLATFORM_BOARD MATCHES "PICO_W")
    include(${CMAKE_CURRENT_LIST_DIR}/targets/picow.cmake)

elseif (EAI_TARGET_PLATFORM_MCU STREQUAL RP2040 AND EAI_TARGET_PLATFORM_BOARD MATCHES "ENV5")
    include(${CMAKE_CURRENT_LIST_DIR}/targets/env5.cmake)


elseif (EAI_TARGET_PLATFORM_MCU STREQUAL RP2350 AND EAI_TARGET_PLATFORM_BOARD MATCHES "PICO")
    include(${CMAKE_CURRENT_LIST_DIR}/targets/pico2.cmake)

elseif (EAI_TARGET_PLATFORM_MCU STREQUAL RP2350 AND EAI_TARGET_PLATFORM_BOARD MATCHES "PICO_W")
    include(${CMAKE_CURRENT_LIST_DIR}/targets/pico2w.cmake)

else ()
    message(FATAL_ERROR
            "Unsupported combination "
            "EAI_TARGET_PLATFORM_MCU=${EAI_TARGET_PLATFORM_MCU} + "
            "EAI_TARGET_PLATFORM_BOARD=${EAI_TARGET_PLATFORM_BOARD}"
    )

endif ()

