= FPGA
:src-dir: ../../..
:imagesdir: {src-dir}/documentation/pics

== Debugging

The link:Vivado_Debugger.adoc[Vivado-Debugger-Guide] provides some information for debugging the FPGA/Flash with help of Vivado.

== Libraries

=== FPGA Configuration Handler

The link:fpgaConfigurationHandler/[FPGA Config Handler library] provides functions to easily download FPGA configuration files from the internet or via USB in the local Flash storage.

=== Middleware

The middleware implementation can be found in link:middleware[the middleware folder].

TIP: Further information about the middleware can be found in the link:https://github.com/es-ude/elastic-ai.creator[elastic-ai.creator repository]

=== Stub

The stub implementation can be found in link:stub[the stub folder].
It provides the counter part for the skeleton defined for the FPGA.

[TIP]
====
It is possible to define your own custom stub implementation for AI accelerator by defining your memory configuration by providing your own `stub_defs.h` file for the `stub_lib`:

.stub.h
[source,c]
----
#ifndef STUB_DEFINES
#define STUB_DEFINES

#ifndef ADDR_COMPUTATION_ENABLE
#define ADDR_COMPUTATION_ENABLE 16
#endif
#ifndef ADDR_SKELETON_INPUTS
#define ADDR_SKELETON_INPUTS 17
#endif
#ifndef ADDR_MODEL_ID
#define ADDR_MODEL_ID 0
#endif
#ifndef BYTES_MODEL_ID
#define BYTES_MODEL_ID 16
#endif

#endif

----

====

IMPORTANT: We currently provide support for version 1 and version 2 of the AI skeleton!

TIP: Further information about the stub can be found in the link:https://github.com/es-ude/elastic-ai.creator[elastic-ai.creator repository]
