# Based on https://github.com/marketplace/actions/git-clang-format-action

name: "format code"

# run every push
on:
  push:
    branches:
      - gh-apply-clang

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - name: Get files to apply Clang
        run: export SRC=$(git ls-tree --full-tree -r HEAD | cut -f 2 | grep -e '\.\(c\|h\)\$' | grep -v ^extern)
      - name: Apply Clang
        run: clang-format -style=file $SRC
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply clang-format based on .clang-format file"
          commit_user_name: Format Bot
          commit_user_email: clang-format@noreply.de
          push_options: "--force"