## base provided by https://github.com/marketplace/actions/clang-format-github-action

name: "format code"

# run on pull requests to develop
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          # make sure the parent commit is grabbed as well, because
          # that's what will get formatted (i.e. the most recent commit)
          fetch-depth: 2
          # format the latest commit
      - uses: RafikFarhad/clang-format-github-action@v2.1.0
        with:
          style: file
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: apply clang-format changes
          branch: ${{ github.head_ref }}