# Based on https://github.com/marketplace/actions/git-clang-format-action

name: "Format code"

# run on every merged pull request in main
on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Get files to apply Clang
        run: echo SRC=$(git ls-tree --full-tree -r HEAD | cut -f 2 | grep -e "\.\(c\|h\)\$" | grep -v ^extern) >> $GITHUB_ENV

      - name: Apply Clang
        run: clang-format -style=file --fallback-style=llvm -i $SRC

      - name: commit changes
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: github-actions
          email: action@github.com
          commit_message: "style: apply clang-format"
          force-add: "true"
