name: "Create Release"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  semantic_release:
    name: Generate Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cocogitto release
        id: release
        uses: cocogitto/cocogitto-action@v4
        with:
          command: bump
          args: --auto
          git-user: "Intelligent Embedded Systems Lab @ UDE"
          git-user-email: "no-reply.ies@uni-due.de"
      - name: Generate Changelog
        id: changelog
        uses: cocogitto/cocogitto-action@v4
        with:
          command: changelog
          args: --at ${{ steps.release.outputs.version }} --template full_hash

      - name: Upload github release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ github.token }}
          body_path: ${{ steps.changelog.outputs.stdout }}
          tag_name: ${{ steps.release.outputs.version }}
