name: "Create Release"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  semantic_release:
    name: Generate Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cocogitto release
        id: release
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true
          git-user: "Intelligent Embedded Systems @ UDE"
          git-user-email: "no-reply@ies.uni-due.de"
      - name: Generate Changelog
        run: |
          cog changelog --at ${{ steps.release.outputs.version }} \
            -t full_hash > GITHUB_CHANGELOG.md
      - name: Upload github release
        uses: softprops/action-gh-release@v1
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}
