name: "PR Validation"
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - "main"

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: devenv
      - name: install devenv.sh
        run: nix profile add nixpkgs#devenv

      - name: activate devenv shell and test environment
        run: devenv test

      - name: run checks
        run: devenv tasks run -m before check
